AObuchow/Eclipse-Spectrum-Theme

- Modern Dark Theme Product/Product Configuration.product
- Modern Dark Theme/css/Modern_Dark.css
- Modern Dark Theme/css/color_definitions.css
- Modern Dark Theme/css/default_overrides.css
- Modern Dark Theme/css/preference_styles.css
- Modern Dark Theme/css/tabstyle.css
> Add license info in .product and license headers

- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/tabstyle.css
> Improve & organize tab styling a bit

- com.aobuchow.themes.moderndark/css/preference_styles.css
> Improve text compare colors

- com.aobuchow.themes.moderndark/css/default_overrides.css
> Fix tree and table header foreground color

- com.aobuchow.themes.moderndark.feature/feature.xml
Fix #19 since the product has been removed.
> Add license to feature

- com.aobuchow.themes.moderndark/css/Modern_Dark.css
- com.aobuchow.themes.moderndark/css/default_overrides.css
> Improve Maven form editor styling

- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/preference_styles.css
Fix #13
Fix #40
Part of #36
Signed-off-by: Andrew Obuchowicz aobuchow@redhat.com
> Incorrectly styled lists, Marketplace fixes, Javadoc fix

- com.aobuchow.themes.moderndark/META-INF/MANIFEST.MF
- com.aobuchow.themes.moderndark/css/color_definitions.css
- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/tabstyle.css
- com.aobuchow.themes.moderndark/plugin.xml
> Allow modification of Project Explorer font & Accent color

- com.aobuchow.themes.moderndark/css/color_definitions.css
- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/tabstyle.css
add background color, base color and tab hover color preferences
> Organize colors, add more color preferences

- com.aobuchow.themes.moderndark/css/drag_style.css
- com.aobuchow.themes.moderndark/css/preference_styles.css
> Add drag styling, fix console colors a bit, improve marketplace a bit

- com.aobuchow.themes.moderndark/css/drag_style.css
- com.aobuchow.themes.moderndark/css/preference_styles.css
> Marketplace font fix

- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/tabstyle.css
> Improve ctabfolder toolbars

- com.aobuchow.themes.moderndark/css/Modern_Dark.css
- com.aobuchow.themes.moderndark/css/preference_styles.css
The actual colors used could be changed/improved but this should be
better for now.
Fix #32
> Improve marketplace styling for categories & notifications

- com.aobuchow.themes.moderndark/css/default_overrides.css
> Set progress indicator background color

- com.aobuchow.themes.moderndark/css/tabstyle.css
> Fix issue with tab toolbar background when resizing

- com.aobuchow.themes.moderndark/css/default_overrides.css
- com.aobuchow.themes.moderndark/css/tabstyle.css
lighten tables as well
Fix #63
> Fix debug variables view shell background color,lighten lists

- com.aobuchow.themes.moderndark/css/preference_styles.css
> Fix javadoc foreground font color

- com.aobuchow.themes.moderndark/css/preference_styles.css
> Console color preference spacing fix

- com.aobuchow.themes.moderndark/css/preference_styles.css
Haven't tested how they look, they probably will need to be tweaked.
Part of #78
> Add pydev colors & preferences

- com.aobuchow.themes.moderndark/css/preference_styles.css
> Add Eclemma colors

- com.aobuchow.themes.moderndark/css/preference_styles.css
> Improve pydev color preferences

- com.aobuchow.themes.spectrum.feature/feature.xml
- com.aobuchow.themes.spectrum/META-INF/MANIFEST.MF
- pom.xml
- releng/pom.xml
Wow, so much progress in one commit :O
> Bump version to 1.0.0

- .github/git-hooks/pre-commit
- .gitignore
- .prettierignore
- .prettierrc.json
- com.aobuchow.themes.spectrum/.externalToolBuilders/Prettier-Format.launch
- com.aobuchow.themes.spectrum/.project
- package-lock.json
- package.json
> Use prettier to format CSS

- .github/git-hooks/pre-commit
- .gitignore
- .prettierignore
- .prettierrc.json
- com.aobuchow.themes.spectrum/.externalToolBuilders/Prettier-Format.launch
- com.aobuchow.themes.spectrum/.project
- package-lock.json
- package.json
> Add prettier to project

- com.aobuchow.themes.spectrum/css/Spectrum.css
- com.aobuchow.themes.spectrum/css/preference_styles.css
- com.aobuchow.themes.spectrum/css/third_party_plugin_styles.css
> Move third-party plugin styles

- com.aobuchow.themes.spectrum/META-INF/MANIFEST.MF
> Add min versison requirement on org.eclipse.e4.ui.css.swt.theme bundle

- com.aobuchow.themes.spectrum.feature/feature.xml
- com.aobuchow.themes.spectrum.preferences/.gitignore
- com.aobuchow.themes.spectrum.preferences/.project
- com.aobuchow.themes.spectrum.preferences/META-INF/MANIFEST.MF
- com.aobuchow.themes.spectrum.preferences/build.properties
- com.aobuchow.themes.spectrum.preferences/plugin.xml
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Activator.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/BrowserUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Messages.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/messages.properties
- com.aobuchow.themes.spectrum/META-INF/MANIFEST.MF
- com.aobuchow.themes.spectrum/css/color_definitions.css
- com.aobuchow.themes.spectrum/css/default_overrides.css
- com.aobuchow.themes.spectrum/css/tabstyle.css
- com.aobuchow.themes.spectrum/plugin.xml
- pom.xml
> Add preference page

- com.aobuchow.themes.spectrum.preferences/META-INF/MANIFEST.MF
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
> Use StyledText to render colorscheme colors

- .gitignore
- com.aobuchow.themes.spectrum.preferences/.classpath
- com.aobuchow.themes.spectrum.preferences/.gitignore
- com.aobuchow.themes.spectrum.preferences/META-INF/MANIFEST.MF
- com.aobuchow.themes.spectrum.preferences/plugin.xml
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Activator.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorHSL.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PluginStartup.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
- com.aobuchow.themes.spectrum/META-INF/MANIFEST.MF
> Dynamically set the git uncommitted changes font to background color

- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Activator.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorHSL.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PluginStartup.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
> Remove MODIFICATION_TYPE parameter from ColorHSL.modifyProperty()

- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
> Get system colors on the UI thread

- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorHSL.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Messages.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PluginStartup.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/messages.properties
> Add preferences to modify HSL of the theme

- .github/workflows/build-updatesite-branches.yml
- .github/workflows/build-updatesite-master.yml
- com.aobuchow.themes.spectrum.preferences/META-INF/MANIFEST.MF
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/BrowserUtils.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/Messages.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/PreferencesPage.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/SpectrumPreferencesControl.java
- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/messages.properties
Hey @AObuchow,
as discussed yesterday, this is the PR for the layout-update of the preference page.
There are still some things I would like to fix/discuss - maybe not all have to be processed w/ this PR.
* Bug: Eclipse UI doesn't refresh on moving the scale-selection while keeping mouse-down (only on mouse_up events)
* I think this was different before. I think I missed some line that was there before the refactoring.
* No test fragment: For now I gave up adding a test fragment for the control
* I didn't manage to run the (plain) unit tests for the control on Maven
* We can still add this later.
* CSS-Scheme text widget has bright background
* I'm not sure whether this was the case before, as well.
If you got suggestions on improvements, bugs or other feedback, I'd be glad of course to …
> Update Preference Page Layout

- com.aobuchow.themes.spectrum/css/tabstyle.css
Fix #130
Signed-off-by: andrew obuchowicz <andrew@aobuchow.com>
> Fix tab folder rendering in Eclipse 2020-09

- com.aobuchow.themes.spectrum.preferences/src/com/aobuchow/themes/spectrum/preferences/ColorManager.java
- com.aobuchow.themes.spectrum/css/color_definitions.css
- com.aobuchow.themes.spectrum/css/default_overrides.css
- com.aobuchow.themes.spectrum/css/tabstyle.css
- com.aobuchow.themes.spectrum/plugin.xml
based on user selected theme colors
More CSS refactoring is required for certain edge cases such as tables
Fix #46
> Allow light/dark font to be dynamically used

- README.md
PR for issue #96.
Long time no "hear/see/wave", I know. I thought, I'd try and pick up some issues we're still have open. ;)
@AObuchow You can check the effect on my [fork](https://github.com/ingomohr/Eclipse-Modern-Dark-Theme#-installation).
> Use hi-res image for Eclipse Marketplace dnd installer
